version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mysql-net
    container_name: frontend
    hostname: frontend
    restart: always

volumes:
  frontend:
networks:
  mysql-net:
    external: true